FROM debian:9.6-slim

MAINTAINER Clanaid <liang6590@gmail.com>

RUN apt update && apt install \
    git \
    openssh-client -y 

ARG VERSION=0.66.0

ADD https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_extended_${VERSION}_Linux-64bit.tar.gz /tmp/
RUN tar -zxvf /tmp/hugo_extended_${VERSION}_Linux-64bit.tar.gz -C /usr/local/bin

WORKDIR /src

EXPOSE 1313
